services:
  caddy:
    image: caddy:2.8-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - chatbot_network

  api:
    image: python:3-alpine
    command: python /app/fake_server.sh
    volumes:
      - ./fake_server.sh:/app/fake_server.sh
    networks:
      - chatbot_network
    deploy:
      replicas: 3

  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - chatbot_network
    restart: unless-stopped

networks:
  chatbot_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  chroma_data:
