chroma_collection_name: local-rag
chromadb_folder: ./chroma_local_db
chunk_overlap: 200
chunk_size: 2000
claude_haiku_model: claude-3-5-haiku-latest
claude_sonnet_model: claude-3-5-sonnet-20241022
openAIAssistant:
  assistant_id_4o: asst_If9MO1KNNbGGyW9YDH8YKdxn
  assistant_id_4o_mini: asst_mA5llxGZPmThei1d6iQf2Jj3
  vector_store_id: vs_Z642AENwR8hy225V0Ub7Mygd
openAIEmbeddings_model: text-embedding-ada-002
pdf_folder: /home/user/academy/fall_2024/NIS2/Phase2-RAG
